(()=>{
const style=document.createElement('style');style.textContent=`
.code-input{display:flex!important;align-items:center;background:#fff;border:1px solid #d8cfc6;border-radius:10px;overflow:hidden;margin-top:6px;min-width:0}.code-input>span{font-size:19px;font-weight:750;background:#f4ece6;padding:14px 18px;color:#b34028;border-right:1px solid #ded4ca}.code-input input{border:0!important;border-radius:0!important;margin:0!important;min-width:0;width:100%;box-shadow:none!important}.code-input:focus-within{outline:2px solid #ee4d2d;outline-offset:2px}.plain-intro{padding:20px;background:#fff4eb;border-radius:12px}.plain-intro p{margin:8px 0 0;font-size:14px}.overview-head{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-top:25px}.overview-head h3{font-size:24px;margin:8px 0 18px}.overview-status{background:#fff0d9;color:#8e5b16;padding:7px 12px;border-radius:20px;font-size:13px;white-space:nowrap}.overview-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.overview-grid article{padding:20px;border:1px solid #ead9cf;background:#fff;border-radius:14px;border-top:4px solid #ee4d2d}.overview-grid article:nth-child(2){border-top-color:#428458}.overview-grid article:nth-child(3){border-top-color:#79629d}.overview-grid h4{margin:0 0 6px;font-size:20px}.overview-grid p{font-size:14px;color:#817264;margin:0 0 15px}.overview-tags{display:flex;flex-wrap:wrap;gap:8px}.overview-tags span{background:#f5f0e9;padding:6px 8px;border-radius:6px;font-size:13px}.plain-reading{display:flex;gap:14px;justify-content:center;flex-wrap:wrap;padding:18px;background:#f0f5ee;border-radius:10px;margin-top:14px;font-size:14px;color:#3f6447}.overview-note{font-size:13px!important;color:#796e65;line-height:1.7}.plain-purpose{font-size:14px;line-height:1.7;margin-top:10px;color:#706559}.plain-conditions{font-size:14px;line-height:1.7;margin:14px 0}.plain-conditions>div{padding:10px 12px;background:#faf6f1;margin:7px 0;border-radius:8px}.plain-conditions span{font-weight:bold;color:#aa452c;font-size:12px}.plain-conditions p{margin:4px 0}.official-rate-links{border:1px solid #e8d6c8;background:#fff9f2;border-radius:12px;padding:16px;margin:16px 0;font-size:14px;line-height:1.7}.official-rate-links h4{margin:0 0 7px}.official-rate-links a{display:block;color:#b24028;margin:8px 0;text-decoration:none}.official-rate-links a:hover{text-decoration:underline}.shop-query-compact{justify-self:start;min-height:38px!important;padding:8px 16px!important;width:auto!important}.demo-only-banner{font-size:12px;text-align:center;padding:8px;background:#fff4df;color:#87551b}@media(max-width:800px){.overview-grid{grid-template-columns:1fr}.overview-head{align-items:start;flex-direction:column;gap:0}.overview-status{margin-bottom:12px}.plain-reading{justify-content:start}.overview-head h3{font-size:21px}}
`;document.head.append(style);
const rateLinks=document.createElement('div');rateLinks.className='official-rate-links';rateLinks.innerHTML='<h4>想了解优惠前的收费标准？</h4><span>在卖家大学查看原始费率与适用范围。</span><a target="_blank" rel="noopener noreferrer" href="https://shopee.cn/edu/article/20761">海外仓收费标准 · 操作费 / 仓储费 / 异常件处理费 ↗</a><a target="_blank" rel="noopener noreferrer" href="https://shopee.cn/edu/article/25770">佣金、服务费及交易手续费 ↗</a>';
document.querySelector('#cost .form').append(rateLinks);
// Also surface the official explanation beside changing comparison results.
function rates(){const part=document.getElementById('freeTrialPart');if(part&&!part.querySelector('.official-rate-links'))part.append(rateLinks.cloneNode(true));}
window.addEventListener('cost-preview-update',rates);rates();
for(const id of ['projectGgp','skuGgp']){const e=document.getElementById(id);if(!e)continue;e.addEventListener('input',()=>{e.value=e.value.replace(/^\s*S/i,'').trim();});}
})();
(()=>{const s=document.createElement('style');s.textContent=`.project-matrix{overflow:auto;border:1px solid #e5d8cd;border-radius:12px;background:#fff}.project-matrix table{border-collapse:collapse;width:100%;min-width:800px;font-size:13px;line-height:1.7}.project-matrix th,.project-matrix td{padding:14px 16px;text-align:left;vertical-align:top;border-bottom:1px solid #e9e0d7}.project-matrix thead{background:#f0e6db}.project-matrix th:first-child{width:23%}.matrix-program{background:#fbf7f1;border-right:1px solid #e9e0d7}.matrix-program b{font-size:16px}.matrix-program small{display:block;font-weight:normal;color:#8b7867}.matrix-program p{font-weight:normal;color:#746b62;margin:8px 0 0}.matrix-site{color:#a3442e;font-weight:bold;white-space:nowrap}.matrix-reward{color:#326545;width:35%}.station-switch{display:flex;gap:10px;margin:18px 0;flex-wrap:wrap}.station-switch button{flex:1;min-width:140px;padding:14px;border:1px solid #ddcfc2;border-radius:10px;background:#fff;cursor:pointer;text-align:left}.station-switch button span{display:block;margin-top:5px;color:#877363;font-size:12px}.station-switch .selected{border:2px solid #ee4d2d;background:#fff0e9;color:#bb4026}.compact-project-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;align-items:start}.compact-project-grid>.project-entry{margin:0;min-width:0}.compact-project-grid>.project-entry[open]{grid-column:1/-1}.mini-metric{padding:12px;background:#f5f8f2;border-radius:9px;margin:12px 0}.mini-metric>span{display:block;font-size:12px;color:#736d64}.mini-metric>b{display:block;color:#347344;font-size:20px;margin:6px 0}.mini-metric>small{font-size:12px!important;display:block}.mini-track{height:7px;border-radius:8px;background:#dfe5da;overflow:hidden;margin:10px 0}.mini-track i{display:block;height:100%;background:#478759}.compact-performance{margin-top:18px;padding-top:12px;border-top:1px solid #e6ddd3;color:#736453;font-size:14px}.compact-station header{position:static}.compact-project-grid h5{font-size:17px}.compact-station{padding-bottom:18px}@media(max-width:850px){.compact-project-grid{grid-template-columns:1fr 1fr}.project-matrix table{min-width:730px}.project-matrix:before{content:'左右滑动，查看完整项目要求与奖励 →';display:block;padding:10px 14px;color:#9d5a36;font-size:12px}}@media(max-width:520px){.compact-project-grid{grid-template-columns:1fr}.station-switch button{min-width:calc(50% - 10px)}}`;document.head.append(s)})();
(()=>{const s=document.createElement('style');s.textContent='.seller-stage-grid{display:none}';document.head.append(s)})();
(()=>{const s=document.createElement('style');s.textContent=`.priority-focus{margin:18px 0 24px;padding:20px;background:#fff3e9;border:1px solid #f0c4ad;border-radius:12px}.priority-focus h4{font-size:21px;margin:0 0 6px}.priority-focus>p{font-size:13px;color:#847162}.priority-sites{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.priority-sites article{background:#fff;border-radius:9px;padding:14px}.priority-sites article>b{font-size:14px;color:#b4492b}.priority-sites .mini-metric{padding:10px}.trial-next{padding:17px 20px;background:#f3f6ef;border:1px solid #d9e1cf;border-radius:10px;margin:12px 0;font-size:14px;line-height:1.7}.trial-next p{margin:8px 0}.trial-next small{color:#7a756a}.aux-matrix-title th{background:#eeeae5;color:#766e63}.aux-projects{border-top:1px solid #e5dbcf;margin-top:18px;padding-top:16px}.aux-projects>summary{cursor:pointer;color:#776b60;font-size:15px;font-weight:bold;margin-bottom:12px}@media(max-width:850px){.priority-sites{grid-template-columns:1fr 1fr}}@media(max-width:520px){.priority-sites{grid-template-columns:1fr}}`;document.head.append(s)})();

// RM self-declared mode: local preference only; never an authorization credential.
(()=>{
 const KEY='fbs.rm.selfdeclared.v1', TTL=60*24*60*60*1000;
 let state=null;
 const style=document.createElement('style');style.textContent=`.rm-topbar{display:flex;justify-content:flex-end;align-items:center;gap:10px;padding:9px max(18px,calc((100% - 1116px)/2));background:#fff;border-bottom:1px solid #eee4da;font-size:12px}.rm-topbar button{padding:7px 12px;border:1px solid #d7c9bd;border-radius:8px;background:#fff;color:#705344;cursor:pointer;white-space:nowrap}.rm-topbar span{color:#40704b}.rm-dialog{border:1px solid #e6d8cc;border-radius:18px;padding:25px;width:min(440px,calc(100% - 28px));color:#302a24;box-shadow:0 20px 90px #0003}.rm-dialog::backdrop{background:#21190e66}.rm-dialog h2{margin:0 0 12px;font-size:23px}.rm-dialog p{font-size:14px;color:#796c61}.rm-dialog label{display:block;font-size:14px;font-weight:bold}.rm-dialog input{display:block;width:100%;padding:12px;margin:8px 0;border:1px solid #cfc2b6;border-radius:8px;font:inherit}.rm-dialog .rm-actions{display:flex;justify-content:flex-end;gap:9px;margin-top:20px}.rm-dialog button{padding:10px 15px;border:1px solid #ddd0c4;border-radius:8px;cursor:pointer;background:#fff;font:inherit}.rm-dialog .rm-primary{background:#ee4d2d;color:white;border-color:#ee4d2d}.rm-notice{background:#fff5e9;padding:12px;border-radius:9px;font-size:12px;line-height:1.7}.rm-error{color:#b13326!important}.rm-dialog [hidden]{display:none!important}@media(max-width:520px){.rm-topbar{align-items:flex-end}.rm-topbar span{font-size:11px;max-width:220px}}`;document.head.append(style);
 const bar=document.createElement('div');bar.className='rm-topbar';bar.innerHTML='<span id="rmModeLabel"></span><button type="button" id="rmEntry">RM 工作台</button>';document.body.prepend(bar);
 const dialog=document.createElement('dialog');dialog.className='rm-dialog';dialog.setAttribute('aria-labelledby','rmTitle');dialog.innerHTML=`<h2 id="rmTitle">RM 工作台</h2><form id="rmForm"><p>内部查询和演示时，请开启 RM 模式。卖家无需填写邮箱，可继续直接查询 GGP。</p><label for="rmEmail">RM 工作邮箱</label><input id="rmEmail" type="email" autocomplete="email" placeholder="例如 name@shopee.com" required maxlength="254"><div class="rm-notice">无需邮箱验证码。此模式仅用于声明内部使用身份，不授予任何私有数据访问权限。邮箱用于内部访问汇总，本浏览器身份在 60 天后自动失效；关闭网页无需重新填写。</div><p class="rm-error" id="rmError" role="alert" hidden></p><div class="rm-actions"><button type="button" data-rm-close>取消</button><button class="rm-primary" type="submit">开启 RM 模式 · 60 天</button></div></form><div id="rmActive" hidden><p id="rmIdentity"></p><p id="rmExpiry"></p><div class="rm-notice">当前为自行声明的 RM 模式，未验证邮箱。仅记录访问汇总，用于区分内部使用；不授予私有数据权限。换浏览器、微信或清除浏览器数据后需要重新填写。</div><div class="rm-actions"><button id="rmExit" type="button">退出 RM 模式</button><button type="button" class="rm-primary" data-rm-close>继续使用</button></div></div>`;document.body.append(dialog);
 const el=id=>document.getElementById(id);
 function read(){try{const x=JSON.parse(localStorage.getItem(KEY));state=x&&x.version===1&&typeof x.email==='string'&&Number.isFinite(x.expiresAt)&&Number.isFinite(x.startedAt)&&x.expiresAt-x.startedAt===TTL&&x.startedAt<=Date.now()&&x.expiresAt>Date.now()?x:null;if(!state)localStorage.removeItem(KEY)}catch{state=null}return state}
 function render(){read();el('rmModeLabel').textContent=state?'RM 模式 · 自行声明':'';el('rmEntry').textContent=state?'RM 工作台 · 已开启':'RM 工作台';el('rmForm').hidden=!!state;el('rmActive').hidden=!state;if(state){el('rmIdentity').textContent='工作邮箱：'+state.email;el('rmExpiry').textContent='本浏览器有效至 '+new Date(state.expiresAt).toLocaleString('zh-CN',{hour12:false})} }
 el('rmEntry').onclick=()=>{render();el('rmError').hidden=true;dialog.showModal()};dialog.querySelectorAll('[data-rm-close]').forEach(b=>b.onclick=()=>dialog.close());
 el('rmForm').onsubmit=e=>{e.preventDefault();const email=el('rmEmail').value.trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return;const startedAt=Date.now();try{localStorage.setItem(KEY,JSON.stringify({version:1,email,startedAt,expiresAt:startedAt+TTL}));render();window.dispatchEvent(new Event('fbs-rm-mode-change'))}catch{el('rmError').textContent='浏览器未允许保存状态，暂时无法开启。请允许本站存储后重试。';el('rmError').hidden=false}};
 el('rmExit').onclick=()=>{try{localStorage.removeItem(KEY)}catch{}state=null;el('rmEmail').value='';render();window.dispatchEvent(new Event('fbs-rm-mode-change'));dialog.close()};
 // Analytics may read this classification; it must never grant backend access.
 window.FBSUsageContext=Object.freeze({get:()=>({actorType:read()?'rm_self_declared':'unverified_visitor',identityVerified:false})});
 window.addEventListener('storage',e=>{if(e.key===KEY||e.key===null)render()});window.addEventListener('focus',render);document.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});setInterval(render,60000);render();
})();

(()=>{const s=document.createElement('style');s.textContent=`#newsku .sku-filter{background:#f3ece4;align-items:end}#newsku .sku-filter label{display:flex;flex-direction:column;gap:7px;font-size:14px;line-height:20px}#newsku .sku-filter .code-input{height:48px;margin:0;border-radius:8px}#newsku .sku-filter .code-input>span{height:48px;display:flex;align-items:center;padding:0 15px}#newsku .sku-filter input,#newsku .sku-filter select{height:48px;margin:0;padding:10px 12px;border-radius:8px;font-size:15px}#newsku .sku-filter .btn{height:48px;background:#ee4d2d}#newsku .sku-bulk>div{display:flex;flex-wrap:wrap;gap:8px}#newsku .sku-bulk button[data-bulk-tier],#newsku #skuSelectMinimum{background:#fff2e9;color:#b7452d;border:1px solid #ecb7a5;border-radius:8px;padding:10px 13px}#newsku .sku-bulk button[data-bulk-tier]:hover{background:#ee4d2d;color:#fff}`;document.head.append(s)})();