(()=>{
const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const siteNames={MY:'马来西亚',PH:'菲律宾',SG:'新加坡',TH:'泰国'},bars={MY:200,PH:400,SG:50,TH:100};
const programs={
trial:{en:'Free Trial',zh:'新卖家免费试用',step:'01 首次入仓',benefit:{MY:'XS–M 订单免操作费 6 个月',SG:'XS–M 订单免操作费 6 个月',TH:'XS–M 订单免操作费 6 个月，结束后另享 6 个月操作费半价',PH:'2026 年 6 月 30 日后入仓：XS–M 订单免操作费 3 个月'},rule:{MY:'近 3 个月无官方仓入库记录、无库存，且从未享受过 Free Trial；2026 年底前入仓。名单外满足条件的店铺也可申请核验。',SG:'近 3 个月无官方仓入库记录、无库存，且从未享受过 Free Trial；2026 年底前入仓。名单外满足条件的店铺也可申请核验。',TH:'无官方仓历史入库记录及库存（NNWH 入库例外），近 30 天店铺日均单量 ≥10，且在名单；2026 年底前入仓。',PH:'2025 年 7 月前从未在 PH 官方仓入仓，近 30 天店铺日均单量 ≥10，且在名单；2026 年底前入仓。'},action:'先核验 Shop ID、历史入仓与库存，再提品并确认优惠开通日期。',time:'首次入仓不等于当天生效。SG/MY 按周开通，TH 次月 1 日生效，PH 按开白日期；具体截止日以生效记录为准。',stack:'同一笔操作费不能重复减免；与其他项目同时入选，也不代表折扣相乘。',source:'Free Trial 机制，第 1 页'},
shipping:{en:'New Seller Sea Shipping Discount',zh:'新卖家官方头程折扣',step:'01 首次入仓',benefit:{MY:'2026 年 Q3 官方头程 85 折 · 首次出仓日起 90 天',PH:'2026 年 Q3 官方头程 85 折 · 首次出仓日起 90 天',TH:'2026 年 Q3 官方头程 85 折 · 首次出仓日起 90 天',SG:'该项目暂不覆盖新加坡'},rule:'GGP 在该站点的所有店铺均无 CBWH（官方仓）历史入库记录；按 GGP × 站点核验，符合要求后覆盖名下店铺。',action:'发货前核验名单、官方头程首次出仓日期与当前有效价卡。',time:'项目至 2026 年底；Q1 85 折、Q2 8 折、Q3 85 折，Q4 折扣尚未确定。不是从查询日重新获得 90 天。',stack:'新卖家项目机制允许与本项目、Free Trial 一起核验；不与 VIP 头程折扣自动相乘。',source:'官方头程折扣机制，第 1 页'},
acquisition:{en:'New Seller Acquisition',zh:'新卖家入仓成长激励',step:'02 做大官方仓占比',benefit:{MY:'FBS 占比 ≥20%：佣金返现 1%；≥40%：2.5%；≥60%：2.5% + 90 天免仓储费',PH:'FBS 占比 ≥20%：佣金返现 1%；≥40%：2.5%',TH:'FBS 占比 ≥40%：后续适用月份佣金降低 1.5 个百分点',SG:'符合条件可获自动化操作费价卡、尾程优惠、每月 1 万元优惠券（6 个月）及 2026 年内不限次 3PF 搬仓'},rule:{MY:'以名单为主；名单外 GGP 如本站全部店铺此前无官方仓入库，并于 2026/7/1–12/31 首次入仓，也可核验参加。',PH:'固定邀请名单，需在项目窗口内入仓并完成占比目标。',TH:'固定邀请名单，2026/7/28–12/31 入仓并完成占比目标。',SG:'固定邀请名单，2026/7/17–12/31 入仓；自动化价卡另需店铺资格。9 月 FBS 占比低于 60% 可能被移除。'},action:'与客户经理确认入选状态、首次入仓时间、目标和当前是否已转入其他项目。',time:{MY:'当月达标，次月按 FBS NMV 返还佣金；60% 档免仓储由次月配置后生效。',PH:'当月达标，次月按 FBS NMV 返还佣金。',TH:'当月达标，M+2 月 FBS 订单享佣金折扣；不是当月现金返还。',SG:'优惠券须提交信息配置；尾程 SGD 0.68 的每单/每件及有效期存在文件冲突，请确认后使用。'},stack:'通常与 RVP、FBS 占比增长项目去重；SG 占比增长机制对达标店铺自动化价卡另有例外，需确认适用价卡，不重复减免。',source:'New Seller Acquisition 机制，第 1 页'},
pene:{en:'FBS Penetration Increase Program',zh:'官方仓订单占比增长计划',step:'02 做大官方仓占比',benefit:{MY:'FBS 占比 20% / 40% / 60% 档：次月操作费分别减 30% / 40% / 50%；60% 档另有 90 天免仓储',PH:'参与可获 FSS 平台运费费率减免 1.12%；FBS 占比环比提升 5 个百分点可获操作费半价',TH:'占比环比提升 5 个百分点：XS–M 操作费半价；名单内新 SKU 入仓另有优惠券奖励，9 月起按新 SKU GMV 的 10%',SG:'指定店铺达到当月占比目标可获自动化价卡：XS 0.54、S 0.62、M 1.46 SGD/件'},rule:{MY:'9 月起按上月表现：GGP 日均单量 ≥40、FBS 日均单量 >0、FBS 占比 <80%；最终以每月名单为准。',PH:'按上月表现：GGP 日均单量 >100、FBS 日均单量 >0、FBS 占比 <95%；以每月名单为准。',TH:'GGP 日均单量 >50、FBS 日均单量 >0；8/9 月占比 <90%（常规 <85%），另有增长及成本审核条件，以名单为准。',SG:'按店铺核验：有 FBS 订单、占比 <80%，且符合自动化价卡资格；同一 GGP 的店铺目标可能不同。'},action:'把适合的商品转入官方仓，并持续补货避免断货；先确认自己的月度目标再计算差距。',time:{MY:'当月达到并保持对应档位，次月统计发放；项目至 2026 年底。',PH:'占比增长达标后次月发放；项目至 2026 年底。',TH:'两项奖励条件独立。新 SKU 券需提报配置、有效期一个月；不能把优惠券当现金。',SG:'8/9 月达标后在 9/10 月享受价卡；文件写 10 月达标可长期享受，仍须确认店铺获批及价卡生效。'},stack:{MY:'与 RVP、新卖家成长项目去重；享受 Free Trial 的店铺不重复发操作费奖励。',PH:'与 RVP、新卖家成长项目去重；Free Trial 与操作费奖励取更优适用权益。',TH:'可与 RVP 并存；Free Trial 店铺不重复发操作费奖励；与免费搬仓、新卖家成长项目去重。',SG:'可与 RVP 并存；新卖家名单未去重，达标店铺可核验自动化价卡。'},source:'FBS% 增长项目机制，第 1 页（9 月更新）'},
pickup:{en:'Free Pickup',zh:'3PF 库存免费搬仓',step:'01 首次入仓',benefit:{MY:'Free Trial 名单可核验首次免费搬仓；多次资格待确认',PH:'Free Trial 一次搬仓；专项名单可核验多次资格',SG:'Free Trial 一次搬仓；专项名单或新卖家项目可核验额外资格',TH:'Free Trial 不含免费搬仓；专项名单可另行核验'},rule:'用于将当地第三方仓库存转入官方仓，与跨境官方头程是不同服务。名单资格不代表尚未使用、已预约或已批准。',action:'提供 3PF 仓地址、库存和提货计划，向客户经理确认次数、截止日及预约安排；PH 首次至少提前 3 天预约。',time:'PH 专项当前为 Sep / June Renew；SG 来源仍是 August 批次；TH 部分资格有单独截止日。',stack:'MY 表格标记多次但 PDF 写仅一次，次数待确认；TH 专项搬仓与占比增长项目有去重规则。',source:'Free Trial 机制 + Pickup 总表与 PH/SG/TH 专项表'},
vip:{en:'FBS VIP · Local / Regional VIP',zh:'官方仓重点卖家 · 单站 / 跨站 VIP',step:'03–04 进阶 VIP',benefit:{MY:'达标后：Local VIP 佣金返 0.5%–0.8%，Regional VIP 1%–1.5%；另有广告金及头程折扣',PH:'达标后：Local VIP 佣金返 0.5%–0.8%，Regional VIP 1%–1.5%；另有广告金及头程折扣',SG:'达标后：Local VIP 佣金返 1.5%–1.8%，Regional VIP 2%–2.5%；另有广告金及头程折扣',TH:'达标后有广告金及头程折扣；本机制未列 TH 佣金返点'},rule:'Local VIP：单站 GGP 的 FBS 日均单量达到门槛并获月度提名、承诺目标。Regional VIP：四站同时达到门槛；Local 升 Regional 需连续 2 个月四站均达标，再于次月提名。',action:'先稳定单站 FBS 订单量，再与客户经理确认基础/挑战目标；四站持续经营后争取 Regional VIP。',time:'当月达标，次月发放。基础与挑战奖励二选一；头程价卡于次月第一周生效、适用于随后一个月。连续两月未达要求可能降级或退出。',stack:'Local 达标头程 9 折；Regional 达标头程 75 折（2026/7 起四站）。广告金返还 15%–20% / 25%–30%，各站有上限。PH 还需核验占比不下降，TH 还需广告投入率不下降。',source:'FBS VIP 机制，2026/8/17 更新，第 3、7–9 页'}
};
function text(v,s){return typeof v==='string'?v:v[s]||'';}
let data=null,seq=0;
function status(id,r){if(!r)return ['了解条件','neutral'];if(id==='trial')return r.trialShops?['有 '+r.trialShops+' 家店铺在名单','good']:['未命中名单','neutral'];if(id==='vip')return r.vip.length?['本月 '+(r.vip[0].type==='Regional VIP'?'跨站 VIP':'单站 VIP')+' 名单','good']:r.hasHistoricalVip?['仅有历史名单','wait']:['可争取月度提名','neutral'];if(id==='pene')return r.pene.length?['本月名单 · '+r.pene.length+' 条','good']:['本月未命中名单','neutral'];if(id==='acquisition')return r.acquisition.length?['入选记录 · 生效需核验','good']:['未命中邀请名单','neutral'];if(id==='shipping')return r.shipping.length?['入选记录 · 有效期需核验','good']:['未命中名单','neutral'];if(id==='pickup')return r.pickup&&(r.pickup.first||r.pickup.multiple)?['有资格记录 · 未核实使用','good']:['未命中资格记录','neutral'];}
function specifics(id,r,s){if(!r)return '';let t=[];
if(id==='pene'&&r.pene.length){if(s==='SG'){t.push('本月匹配 '+r.pene.length+' 条店铺记录，请按 Shop ID 与客户经理逐店核验目标，不合并店铺占比。');r.pene.slice(0,8).forEach((x,i)=>t.push('店铺记录 '+(i+1)+'：当前占比 '+(x.current??'待补充')+'%，目标 '+(x.target??'待补充')+'%。'));if(r.pene.length>8)t.push('更多店铺目标请联系客户经理核验。');}else{const x=r.pene[0];t.push('本月占比 '+(x.current??'待补充')+'%；上月 '+(x.previous??'待补充')+'%。'+(x.current!==null&&x.previous!==null?' 环比 '+(x.current-x.previous).toFixed(2)+' 个百分点。':''));}if(r.pene.some(x=>x.removal))t.push('表内提示有次月移除风险，请尽快确认。');t.push('月中表现为进度，不是月底获奖结论。');}
if(id==='vip'&&r.vip.length)r.vip.forEach(x=>t.push(r.vip.length>1?'存在多条当月 VIP 记录，请客户经理确认适用目标。':'本月基础目标 '+(x.baseline??'待补充')+' / 挑战目标 '+(x.stretch??'待补充')+' 单/日；当前 '+(x.actual??'待补充')+' 单/日。'));
if(id==='acquisition'&&r.acquisition.some(x=>x.excluded))t.push('表内存在转项目/去重标记，请确认后再申请本项目奖励。');
if(id==='shipping'&&r.shipping.length){const ds=[...new Set(r.shipping.map(x=>x.firstOutbound).filter(Boolean))];t.push(ds.length?'表内首次官方头程出仓：'+ds.join(' / ')+'；请核对 90 天价卡截止日。':'表内缺少首次官方头程出仓日期，暂不能判定 90 天优惠仍有效。');}
if(id==='pickup'&&r.pickupDetail){if(r.pickupDetail.end)t.push('专项表截止日：'+r.pickupDetail.end+'；过期后需重新确认。');t.push('专项批次：'+r.pickupDetail.batch+'。名单及历史操作状态不能证明当前可用次数。');}
return t.length?'<div class="personal">'+t.map(x=>'<p>'+E(x)+'</p>').join('')+'</div>':'';}
const roadmaps={
 MY:{start:'Free Trial 免费试用 · XS–M 订单免操作费 6 个月',entry:'近 3 个月无入库、无库存，且从未享受 Free Trial；2026 年底前入仓。',branch:'试用结束后，核验是否进入增长项目及当月目标',paths:[['入选 Pene，达到并保持对应档位','占比 20% / 40% / 60% → 次月操作费减 30% / 40% / 50%；60% 档另有 90 天免仓储。','green'],['未入选或当月未达档位','不能直接享受 Pene 奖励；核验当前有效价卡，争取下次月度名单。','muted']],extra:'新卖家成长项目可提供佣金返现，但与 Pene / VIP 去重；应先选适用项目，不能把两份奖励直接相加。'},
 PH:{start:'Free Trial 免费试用 · 6/30 后入仓免操作费 3 个月',entry:'2026 年 6/30 前入仓对应 6 个月；需在邀请名单且满足历史入仓、日均单量条件。仅限 XS–M。',branch:'试用结束：先看 GGP 是否在 Pene 名单、是否达增长目标',paths:[['在 Pene 名单，环比提升 5 个百分点','适用操作费半价；参与项目另有 FSS 平台运费费率减免 1.12%。','green'],['Pene 未达标 / 未入选，但满足旧批次条件','仅 6/30 前入仓且试用结束时近 30 天店铺 FBS 占比 ≥30%：优惠价卡再享 3 个月半价。','amber'],['不满足以上进阶条件','按 Free Trial 后续优惠价卡至 2026 年底；未入选 Pene，不推定享有 FSS 减免。','muted']],extra:'同一笔操作费优惠取更优适用权益，不重复减免。FSS 是平台运费费率优惠，不是佣金返现。'},
 SG:{start:'Free Trial 免费试用 · XS–M 订单免操作费 6 个月',entry:'近 3 个月无入库、无库存，且从未享受 Free Trial；2026 年底前入仓。',branch:'试用结束后，逐店核验增长名单与自动化价卡目标',paths:[['指定店铺在名单，达到当月占比目标','按自动化价卡享优惠：XS 0.54 / S 0.62 / M 1.46 SGD/件。8/9 月达标对应 9/10 月价卡。','green'],['未达标或店铺未获价卡资格','不能直接套用自动化价卡；先补齐店铺资格，按本月目标推进。','muted']],extra:'机制写 10 月达标可长期享自动化价卡，仍须核验配置。SG 按 Shop 评估，不能用 GGP 总体达标代替每家店铺达标。'},
 TH:{start:'Free Trial 免费试用 · XS–M 订单免操作费 6 个月',entry:'无官方仓历史入库及库存（NNWH 例外）、近 30 天店铺日均 ≥10 单，并在名单；入库次月起生效。',branch:'试用结束后，基础延续优惠与 Pene 奖励分别核验',paths:[['Free Trial 后续权益','再享 6 个月操作费半价；以实际开白起止记录为准。','green'],['GGP 入选 Pene，占比环比增加 5 个百分点','可核验 XS–M 操作费半价；已在试用或已有相同价卡，不重复减免。','green'],['GGP 入选 Pene，当月有新 SKU 入仓','9 月起另有新 SKU GMV 10% 的优惠券奖励；与占比增长目标独立，需提报。','amber']],extra:'TH Pene 可与 VIP 并存，但与新卖家成长、专项免费搬仓去重；并存不代表同笔费用重复奖励。'}
};
function roadmap(s){const m=roadmaps[s];return '<section class="station-road"><div class="site-heading"><h3>'+siteNames[s]+' <span>'+s+'</span></h3><span class="road-label">基础 → 进阶 → 高阶</span></div><div class="route-node route-start"><span class="route-step">基础 · FIRST INBOUND</span><h4>'+m.start+'</h4><p>'+m.entry+'</p></div><div class="route-arrow" aria-hidden="true">↓</div><div class="route-decision">'+m.branch+'</div><div class="route-arrow" aria-hidden="true">↓ 按适用条件进入分支</div><div class="route-branches" style="--branches:'+m.paths.length+'">'+m.paths.map(p=>'<article class="route-node '+p[2]+'"><span class="route-step">进阶 · 条件分支</span><h4>'+p[0]+'</h4><p>'+p[1]+'</p></article>').join('')+'</div><p class="route-extra">'+m.extra+'</p><div class="route-arrow" aria-hidden="true">↓ 做大 FBS 订单，申请月度提名</div><div class="route-vip"><article class="route-node"><span class="route-step">高阶 · LOCAL VIP</span><h4>单站重点卖家</h4><p>'+s+' 站 GGP 的 FBS 日均订单 ≥'+bars[s]+' 单，获提名并承诺月度基础 / 挑战目标。'+(s==='PH'?'另需核验 FBS 占比不下降。':s==='TH'?'另需核验广告投入率不下降。':'')+'</p></article><div class="vip-arrow" aria-hidden="true">→</div><article class="route-node"><span class="route-step">高阶 · REGIONAL VIP（RVP）</span><h4>跨站重点卖家</h4><p>Local 升 Regional：连续 2 个月四站均达到 MY 200 / PH 400 / SG 50 / TH 100 单/日，次月提名并承诺 Regional 目标。</p></article></div><p class="growth-note">路线展示可争取的方向，不表示必须参加所有项目。VIP 门槛是提名条件；具体月度目标、开白与发放另行核验。</p></section>';}
function availablePrograms(r,s){if(!r)return [];const ids=[];if(r.trialShops)ids.push('trial');
 const today=new Date().toISOString().slice(0,10);const activeShipping=r.shipping.some(x=>{if(!x.firstOutbound)return true;const d=Date.parse(x.firstOutbound);return Number.isFinite(d)&&Date.now()<d+90*86400000;});
 if(s!=='SG'&&activeShipping)ids.push('shipping');
 const pickupActive=r.pickup&&(r.pickup.first||r.pickup.multiple)&&(!r.pickupDetail?.end||r.pickupDetail.end>=today);
 if(pickupActive)ids.push('pickup');
 const acq=r.acquisition.some(x=>!x.excluded),vip=r.vip.length>0,pene=r.pene.length>0;
 // Current VIP membership takes precedence over mutually exclusive invitation lists.
 if(acq&&!vip&&(!pene||s==='SG'))ids.push('acquisition');
 if(pene&&(!(vip&&['MY','PH'].includes(s)))&&(!(acq&&['MY','PH','TH'].includes(s)))&&(!(s==='TH'&&pickupActive&&r.pickup.multiple)))ids.push('pene');
 if(vip)ids.push('vip');return ids;}
function conflicts(r,s){const notes=[];const acq=r.acquisition.some(x=>!x.excluded),pene=r.pene.length>0;if(acq&&pene&&s!=='SG'&&!r.vip.length)notes.push('同时命中新卖家成长与 Pene 互斥名单，暂不展示为可享奖励。请客户经理确认当前有效项目。');if(s==='TH'&&pene&&r.pickup?.multiple)notes.push('TH Pene 与专项免费搬仓存在去重要求，需确认当前项目后再核验 Pene 奖励。');if(r.hasHistoricalVip)notes.push('仅有历史 VIP 记录，未列为本月可享项目。');return notes;}

function render(){const selection=$('#growthSite').value,chosen=selection==='ALL'?Object.keys(siteNames):[selection];$('#stationRoadmaps').innerHTML=chosen.map(roadmap).join('');let html='';
if(data?.status!=='matched'){$('#programResults').innerHTML='<div class="empty-programs">输入 GGP 并查询后，这里只展示匹配主体的可申请 / 推进项目及相关店铺。未查询时不展示通用项目卡片。</div>';return;}
for(const s of chosen){const r=data.sites.find(x=>x.site===s);if(!r)continue;const ids=availablePrograms(r,s),notes=conflicts(r,s);html+='<section class="site-programs"><div class="site-heading"><h3>'+siteNames[s]+' <span>'+s+'</span></h3><p>'+ids.length+' 个有名单依据的项目 · 实际生效仍需核验</p></div>'+notes.map(n=>'<p class="notice">'+E(n)+'</p>').join('');
if(!ids.length){html+='<div class="empty-programs">本次未找到可直接展示的项目。可能为未入选、已过期或互斥状态待确认；可按上方路线与客户经理确认下一阶段。</div></section>';continue;}
html+='<div class="program-grid">';for(const id of ids){const p=programs[id],[label,tone]=status(id,r);html+='<article class="program"><div class="program-top"><span>'+p.step+'</span><span class="program-status '+tone+'">'+E(label)+'</span></div><h4>'+p.zh+'</h4><div class="program-en" lang="en">'+p.en+'</div><p class="program-benefit">'+E(text(p.benefit,s))+'</p>'+specifics(id,r,s)+shopTable(id,r,s)+'<p class="next-action"><b>下一步：</b>'+E(p.action)+'</p><details><summary>参加条件、发放时间与叠加规则</summary><dl><dt>参加条件</dt><dd>'+E(text(p.rule,s))+'</dd><dt>何时生效</dt><dd>'+E(text(p.time,s))+'</dd><dt>能否叠加</dt><dd>'+E(text(p.stack,s))+'</dd></dl><small>依据：'+E(p.source)+'</small></details></article>';}
html+='</div></section>';}
$('#programResults').innerHTML=html;}
function shopTable(id,r,s){const shops=id==='trial'?(r.trialDetails||[]):id==='pene'&&s==='SG'?r.pene.filter(x=>x.shopId):[];if(!shops.length)return '<p class="shop-scope">'+(id==='trial'?'名单缺少店铺字段，请补充。':'本项目按 GGP × 站点核验；来源未提供对应店铺时，不推定其他店铺适用。')+'</p>';return '<details class="shop-details"><summary>查看对应店铺（'+shops.length+' 家）</summary><div class="shop-table-scroll"><table class="shop-table"><thead><tr><th>Shop ID</th><th>Username 店铺名</th>'+(id==='pene'?'<th>当月占比 / 目标</th>':'')+'</tr></thead><tbody>'+shops.map(x=>'<tr><td>'+E(x.shopId)+'</td><td>'+E(x.username||'来源未填写')+'</td>'+(id==='pene'?'<td>'+E(x.current??'待补')+'% / '+E(x.target??'待补')+'%</td>':'')+'</tr>').join('')+'</tbody></table></div></details>';}
async function search(e){e?.preventDefault();const version=++seq,ggp=$('#growthGgp').value.trim();data=null;render();if(!ggp){$('#growthStatus').textContent='选择站点查看成长路线；输入 GGP 后仅展示匹配项目。';return;}$('#growthStatus').textContent='正在核验项目名单…';$('#growthSearch').disabled=true;try{const res=await fetch('https://el-fbs-roster-api.summer-li01.workers.dev/api/incentives',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ggp,site:$('#growthSite').value}),signal:AbortSignal.timeout(15000)});if(!res.ok)throw Error(res.status===429?'查询过于频繁，请一分钟后再试。':'暂时无法查询，请稍后重试。');const d=await res.json();if(version!==seq)return;data=d;$('#growthStatus').textContent=({matched:(d.match==='fuzzy'?'已模糊匹配，请核对主体输入；':'已匹配主体；')+'下方显示名单记录，不代表奖励已生效。快照 '+d.updatedAt+'，月度目标 '+d.month+'。',not_found:'没有匹配到该 GGP。请补充营业主体名称；不展示项目卡片；上方路线可作为下一步参考。',ambiguous:'名称匹配到多个主体，请补充更完整的 GGP 名称后查询。',too_short:'请至少输入 4 个有效字符，并尽量包含主体独有名称。'})[d.status]||'查询结果暂不可用。';render();}catch(err){if(version===seq)$('#growthStatus').textContent=err.message==='The operation was aborted due to timeout'?'查询超时，请稍后重试。':err.message;}finally{if(version===seq)$('#growthSearch').disabled=false;}}
$('#growthForm').addEventListener('submit',search);$('#growthSite').addEventListener('change',()=>search());$('#growthGgp').addEventListener('input',()=>{seq++;data=null;$('#growthSearch').disabled=false;$('#growthStatus').textContent='输入已更改，点击查询后核验；当前仅显示站点路线，项目卡片已清空。';render();});render();
})();
// Keep the new tab directly shareable while preserving the existing tabs.
document.querySelectorAll('.tabs button').forEach(b=>b.addEventListener('click',()=>history.replaceState(null,'','#'+b.dataset.page)));
if(['guide','cost','growth'].includes(location.hash.slice(1)))document.querySelector('.tabs button[data-page="'+location.hash.slice(1)+'"]').click();
