(()=>{
const $=id=>document.getElementById(id),E=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const {mpSkuId,itemLink,minimumPlan,tierPlan,exportCSV}=window.NewSkuPlan;
const sites={MY:'马来西亚',SG:'新加坡',PH:'菲律宾'},money=(n,c)=>({USD:'US$',MYR:'RM ',PHP:'₱'}[c]||'')+Number(n).toLocaleString('en-US',{maximumFractionDigits:2}),fmt=n=>Number(n).toLocaleString('en-US');
const btn=document.createElement('button');btn.dataset.page='newsku';btn.textContent='新品入仓激励';document.querySelector('.tabs').append(btn);
const panel=document.createElement('main');panel.id='newsku';panel.className='page wrap';document.querySelector('.footer').before(panel);
btn.onclick=()=>{document.querySelector('.tabs .on')?.classList.remove('on');document.querySelector('.page.on')?.classList.remove('on');btn.classList.add('on');panel.classList.add('on');history.replaceState(null,'','#newsku')};
const rules={
 SG:{reward:'US$20 / Model',type:'免费广告金',brief:'在有效批次内入够名单要求数量，达标 Model 可获得广告金。',window:'9 月批次 · 截止 2026-09-30',steps:['确认名单与最低入仓量','批次内累计达到 45 DOC','审核后领取广告金'],note:'45 DOC 是按名单取数时的销售速度设定的备货量，不是等待 45 天。V-SKU 需申请白名单、确认映射及单独最低入仓量。',fine:'历史批次已达标的 Model 不重复领奖；批次内只入了部分数量，不能直接跨批次累计。发放月份请向客户经理确认。'},
 MY:{reward:'18 / 27 / 36 DOC',type:'FBS 店铺优惠券',brief:'入够对应档位的数量，可争取不同券额；36 DOC 档需卖家共补。',window:'项目至 2026-12-31 · 具体批次窗口另核验',steps:['选择 Model 与目标档位','批次窗口内累计入仓','核验券额与共补安排'],note:'18、27、36 DOC 是三个备货目标，不是需要等待的天数。8 月初邀请批次延长至 9 月底；其他批次以确认的截止日为准。',fine:'36 DOC 券总额对应旧基准 140%，其中平台 120%、卖家 20%：例如券额 RM140，平台 RM120，卖家 RM20。三个档位择一，不叠加。'},
 PH:{reward:'3 档入仓奖励',type:'FBS 店铺优惠券',brief:'按每个 Model 的独立考核窗口累计，达到对应数量后核验券额；各档金额以站点明细表为准。',window:'项目至 2026-10-31 · 每个 Model 独立窗口',steps:['确认 Model、批次与目标','在所属考核窗口内入够','每月两次审核，核对发券'],note:'1–15 日首次入仓：按当月 1 日至月末累计；16 日后首次入仓：按当月 16 日至次月 15 日累计。跨批次与特殊情况须另核验。',fine:'一般针对已有 FBS 店铺的未入仓 Model，另有提名例外。V-SKU 需要确认母 SKU 映射及分配数量；是否在名单中不能替代最终审核。'}
};
panel.innerHTML=`<section class="sku-heading"><div><p class="kicker">04 / NEW SKU INBOUND</p><h2>让下一批新品，带着激励入仓</h2><p>找到可参加的 Model，选好入仓目标，看清能争取的广告金或店铺券。</p></div><span class="sku-demo">备货规划 · 未提交入仓计划</span></section>
<div class="sku-site-rules">${['SG','MY','PH'].map(s=>`<button data-rule-site="${s}"><span>${s} · ${sites[s]}</span><b>${rules[s].reward}</b><small>${rules[s].type}</small></button>`).join('')}</div>
<div class="sku-filter"><label>GGP Code<span class="code-input"><span>S</span><input id="skuGgp" inputmode="numeric" maxlength="16" placeholder="示例：12345" autocomplete="off" aria-label="新品 GGP Code 数字部分"></span></label><label>目标站点<select id="skuSite"><option value="ALL">全部站点</option>${Object.entries(sites).map(([s,n])=>`<option value="${s}">${n} ${s}</option>`).join('')}</select></label><button id="skuQuery" class="btn">查找我的新品</button></div>
<div class="sku-query-info" id="skuQueryInfo" role="status" aria-live="polite">输入 GGP 后，仅显示匹配编号的名单商品。实际订单量与 ADO 不在本页展示。</div>
<div id="skuMechanism"></div><div id="skuWorkspace"></div>
<details class="sku-explainer"><summary>先弄清楚：SKU、Model 和奖励怎么算？</summary><p><b>这里的新品指首次入 FBS 的商品规格，不一定是新上架商品。Item 是商品，Model 是具体规格。</b>同一商品的不同颜色、规格，可能对应不同的入仓目标与奖励。MP_SKU_ID = Item ID_Model ID，搭配站点和 Shop ID 定位具体规格。下载表中的 mt_sku_id 使用同一组合值。</p><p><b>DOC = 备货可覆盖的销售天数。</b>页面直接展示名单要求的入仓件数，不需要你自己用销量计算，也不必等待这些天数。</p><p><b>这些是推广支持，不是现金利润。</b>SG 广告金与 MY / PH 店铺券分开统计，不跨币种相加，也不直接减去费用测算里的物流成本。同一 Model 的档位择一，不能叠加。</p><p>名单和数量参考：2026-09-13。参与意向、入仓达标与实际发奖是三个不同状态。优惠以有效批次、入仓记录和最终审核为准。</p></details>`;
let data=null,selected=new Set(),tierChoices=new Map(),request=0,page=1,filter='all',search='';
function mechanism(){const s=$('skuSite').value;document.querySelectorAll('[data-rule-site]').forEach(b=>b.classList.toggle('active',b.dataset.ruleSite===s));const r=rules[s];$('skuMechanism').innerHTML=r?`<section class="sku-mechanism"><div><span class="sku-site-badge">${s} · ${sites[s]}</span><b>${r.type}</b><span class="sku-muted">${r.window}</span></div><p>${r.brief}</p><ol>${r.steps.map((t,i)=>`<li><span>${i+1}</span>${t}</li>`).join('')}</ol><details><summary>查看本站规则与注意事项</summary><p>${r.note}</p><p>${r.fine}</p></details></section>`:s==='TH'?'<div class="sku-empty">目前提供的 New SKU 名单与机制覆盖 SG、MY、PH，尚无 TH 规则与名单，暂不推定可参加。</div>':'';}
function tier(r){return r.tiers.find(t=>t.doc===tierChoices.get(r.id))||r.tiers.find(t=>t.doc===27)||r.tiers[0]}
function card(r){const t=tier(r),chosen=selected.has(r.id),unavailable=!t;return `<article class="sku-product ${chosen?'chosen':''}"><header><span class="sku-site-badge">${r.site} ${sites[r.site]}</span><span>${E(r.shopName||'名单店铺')} · Shop ${E(r.shopId)}</span></header><div class="sku-product-title"><div class="sku-box-icon" aria-hidden="true">◇</div><div><h3>${E(r.modelName||'Model '+r.modelId)}</h3><p>${E(r.itemName||'商品名称未提供，以 MP_SKU_ID 核对')}</p><div class="sku-ids"><span>MP_SKU_ID <b>${E(mpSkuId(r))}</b></span>${itemLink(r)?`<a class="sku-item-link" href="${E(itemLink(r))}" target="_blank" rel="noopener noreferrer">查看商品 ↗</a>`:''}</div></div></div>
${unavailable?'<div class="sku-warning">总名单已收录，站点目标或奖励明细缺失，暂不计算奖励。</div>':`<div class="sku-tier-label">选择本次计划目标 <small>各档择一；券额／广告金不是现金返还</small></div><div class="sku-tiers">${r.tiers.map(x=>`<button data-tier="${x.doc}" data-id="${E(r.id)}" aria-pressed="${t.doc===x.doc}" class="${t.doc===x.doc?'active':''}"><span>${x.doc} DOC</span><b>${fmt(x.qty)} 件</b><small>可争取 ${money(x.amount,r.currency)} ${r.rewardType}${!x.confirmed?' · 待核验':''}</small></button>`).join('')}</div>
${r.site==='MY'&&t.doc===36?`<div class="sku-cofund"><span>券总额 <b>${money(t.amount,'MYR')}</b></span><span>平台补贴约 <b>${money(t.amount*6/7,'MYR')}</b></span><span>卖家共补约 <b>${money(t.amount/7,'MYR')}</b></span></div>`:''}
${!t.confirmed?'<p class="sku-warning">此档金额与机制比例不一致，暂不计入计划奖励，确认后再执行。</p>':''}
<footer><span>${/^no$/i.test(r.participation)?'此前记录为未同意，参加前需重新确认。':/^yes$/i.test(r.participation)?'已记录参与意向，不代表奖励已生效。':'参加前先与客户经理确认意向。'}${r.vsku?' V-SKU：需核验映射和最低入仓量。':''}</span><button data-select="${E(r.id)}" aria-pressed="${chosen}" class="${chosen?'selected':''}">${chosen?'✓ 已加入计划':'＋ 加入本次计划'}</button></footer>`}</article>`}
function workspace(){if(!data){$('skuWorkspace').innerHTML='<section class="sku-empty"><span class="sku-empty-icon">＋</span><h3>下一批哪些新品值得优先入仓？</h3><p>输入 GGP 和站点，查看名单内 Model、入仓目标与对应激励。</p><p>先选商品，再确认数量，最后核验奖励。</p></section>';return}
if(!data.rows.length){$('skuWorkspace').innerHTML=`<section class="sku-empty"><h3>该编号在${$('skuSite').value==='ALL'?'当前名单':E(sites[$('skuSite').value])}暂无 New SKU 记录</h3><p>不代表永久无资格。可切换已收录站点，或请客户经理核验下一批名单。</p><div>${data.availableSites.map(s=>`<button class="btn" data-switch="${s}">${sites[s]} ${s}</button>`).join(' ')}</div></section>`;return}
 const views=data.rows.filter(r=>(filter==='all'||filter==='selected'&&selected.has(r.id))&&(!search||[mpSkuId(r),r.modelId,r.itemId,r.shopId,r.itemName,r.modelName].join(' ').toLowerCase().includes(search.toLowerCase())));
 const pages=Math.max(1,Math.ceil(views.length/8));page=Math.min(page,pages);
 $('skuWorkspace').innerHTML=`<div class="sku-results-heading"><div><h3>${E(data.name)}</h3><p><b>${data.rows.length}</b> 个名单 Model · <b>${new Set(data.rows.map(r=>r.site+'|'+r.shopId)).size}</b> 家店铺 · 当前${$('skuSite').value==='ALL'?'全部站点':E(sites[$('skuSite').value])}<br><small>名单命中仅表示可进一步核验，不表示已获批或已发奖。</small></p></div></div><div class="sku-toolbar"><div><button data-filter="all" class="${filter==='all'?'active':''}">全部 Model</button><button data-filter="selected" class="${filter==='selected'?'active':''}">已选 ${selected.size}</button></div><input id="skuModelSearch" aria-label="筛选商品或Model" placeholder="搜索 MP_SKU_ID、商品或 Shop ID" value="${E(search)}"></div><div class="sku-bulk"><div>${data.rows.some(r=>r.site!=='SG')?[18,27,36].map(d=>`<button type="button" data-bulk-tier="${d}">${d} DOC 档 · 一键全选</button>`).join(''):'<button id="skuSelectMinimum" type="button">45 DOC 档 · 一键全选</button>'}<button id="skuClearSelection" type="button" ${selected.size?'':'disabled'}>清空选择</button></div><small>覆盖当前 GGP＋站点下全部 ${data.rows.length} 个 Model，不受分页及关键词筛选限制；MY / PH 按所选 18、27、36 DOC 档位覆盖当前计划；SG 仅有 45 DOC 档，全部站点时自动保留该档。缺少对应档位的商品跳过。</small><span id="skuBulkStatus" role="status"></span></div><div class="sku-layout"><section id="skuCards">${views.length?views.slice((page-1)*8,page*8).map(card).join(''):'<div class="sku-empty">当前筛选没有商品。</div>'}<div class="sku-pagination"><button data-paging="-1" ${page===1?'disabled':''}>上一页</button><span>${page} / ${pages} 页 · ${views.length} 个 Model</span><button data-paging="1" ${page===pages?'disabled':''}>下一页</button></div></section><aside id="skuPlan" class="sku-plan"></aside></div>`;
 plan();$('skuModelSearch').oninput=e=>{const pos=e.target.selectionStart;search=e.target.value;page=1;workspace();$('skuModelSearch').focus();$('skuModelSearch').setSelectionRange(pos,pos)};
}
function plan(){const rows=data.rows.filter(r=>selected.has(r.id)),totals={},qty=rows.reduce((a,r)=>a+(tier(r)?.qty||0),0);let held=0,cofund=0;
for(const r of rows){const t=tier(r);if(!t?.confirmed){held++;continue}totals[r.site]=(totals[r.site]||0)+t.amount;if(r.site==='MY'&&t.doc===36)cofund+=t.amount/7;}
 $('skuPlan').innerHTML=`<p class="kicker">MY INBOUND PLAN</p><h3>这一批，我想争取</h3><p class="sku-plan-count"><b>${rows.length}</b> 个 Model <span>目标累计 ${fmt(qty)} 件</span></p><small>目标数量，不是从现在起还要新增的数量。</small>${Object.entries(totals).map(([s,n])=>`<div class="sku-plan-reward"><span>${sites[s]} · ${s==='SG'?'广告金':'店铺券总额'}</span><strong>${money(n,s==='SG'?'USD':s==='MY'?'MYR':'PHP')}</strong>${s==='MY'?`<small>平台补贴约 ${money(n-cofund,'MYR')}<br>卖家需共补约 ${money(cofund,'MYR')}</small>`:''}</div>`).join('')||'<div class="sku-plan-placeholder">在左侧选 Model<br>这里自动汇总对应奖励</div>'}${held?`<p class="sku-warning">${held} 个 Model 金额待核验，未计入合计。</p>`:''}<p class="sku-plan-note">全部按所选档位达标的情景预估；未扣除历史已领奖额。不同币种分开展示，不算作净利润或保证收益。</p><button id="skuExport" class="btn" ${rows.length?'':'disabled'}>下载明细</button><span id="skuCopyStatus" role="status"></span><div class="sku-action"><h4>三步把激励落地</h4><ol><li><b>发出计划</b><span>核验所选 Model、批次截止日、V-SKU 映射及可入仓要求。</span></li><li><b>确认目标再发货</b><span>核对目标累计数量；已有入仓记录先确认有效量，避免重复补货。</span></li><li><b>入仓后核验奖励</b><span>确认考核窗口、最终档位及发放。MY 共补金额另行确认。</span></li></ol></div>`;
 $('skuExport').onclick=()=>{const csv=exportCSV(rows,tier),url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='New_SKU_备货明细_'+$('skuSite').value+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);$('skuCopyStatus').textContent=`已下载 ${rows.length} 条明细（CSV，可用 Excel 打开）。`;};
}
async function query(){const ggp=$('skuGgp').value.trim(),site=$('skuSite').value,seq=++request;data=null;selected.clear();tierChoices.clear();page=1;filter='all';search='';workspace();mechanism();if(ggp&&!/^\d{1,16}$/.test(ggp)){$('skuQueryInfo').textContent='请输入完整 GGP Code 的数字部分。';return}if(!ggp){$('skuQueryInfo').textContent='输入 GGP Code 后查看名单内 Model；站点机制可先浏览。';return} $('skuQuery').disabled=true;$('skuQueryInfo').textContent='正在查询名单与站点明细…';try{const d=await FBSQuery.request('/api/new-sku',{ggp,site},{key:'sku',onStatus:t=>{if(seq===request)$('skuQueryInfo').textContent=t}});if(seq!==request)return;if(d.status!=='matched'){$('skuQueryInfo').textContent=({too_short:'请输入完整 GGP Code 的数字部分。',ambiguous:'匹配到多个相近编号，请联系客户经理核对编号。',not_found:'当前 New SKU 名单未找到该编号，请核对编号或联系客户经理。'})[d.status]||'暂时无法匹配，请核对输入。';return}data=d;$('skuQueryInfo').textContent=`已${d.match==='exact'?'准确':'精准'}匹配：${d.name} · 名单读取日期 ${d.updatedAt}`;workspace();}catch(err){if(seq===request)$('skuQueryInfo').textContent=FBSQuery.message(err)}finally{if(seq===request)$('skuQuery').disabled=false}}
panel.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.ruleSite||t.dataset.switch){$('skuSite').value=t.dataset.ruleSite||t.dataset.switch;query()}if(t.dataset.bulkTier){const items=tierPlan(data.rows,Number(t.dataset.bulkTier));selected=new Set(items.map(x=>x.id));tierChoices.clear();items.forEach(x=>tierChoices.set(x.id,x.doc));workspace();$('skuBulkStatus').textContent=`已按 ${t.dataset.bulkTier} DOC 档选择 ${items.length} 个 Model；SG 使用 45 DOC 档。跳过 ${data.rows.length-items.length} 个缺少对应档位的 Model。`;}if(t.id==='skuSelectMinimum'){const items=minimumPlan(data.rows);selected=new Set(items.map(x=>x.id));items.forEach(x=>tierChoices.set(x.id,x.doc));workspace();$('skuBulkStatus').textContent=`已选择 ${items.length} 个 Model 的最低档位${data.rows.length>items.length?'；'+(data.rows.length-items.length)+' 个缺少备货目标，未选入':''}。`;}if(t.id==='skuClearSelection'){selected.clear();workspace();}if(t.dataset.tier){tierChoices.set(t.dataset.id,Number(t.dataset.tier));workspace()}if(t.dataset.select){selected.has(t.dataset.select)?selected.delete(t.dataset.select):selected.add(t.dataset.select);workspace()}if(t.dataset.filter){filter=t.dataset.filter;page=1;workspace()}if(t.dataset.paging){page+=Number(t.dataset.paging);workspace();$('skuCards').scrollIntoView({block:'start',behavior:'smooth'})}});
 $('skuQuery').onclick=query;$('skuSite').onchange=query;$('skuGgp').onkeydown=e=>{if(e.key==='Enter')query()};
$('skuGgp').addEventListener('input',()=>{request++;FBSQuery.cancel('sku');data=null;selected.clear();tierChoices.clear();workspace();$('skuQuery').disabled=false;$('skuQueryInfo').textContent='填写完成后，点击查找我的新品。'});mechanism();workspace();if(window.initialDemoHash==='#newsku'||location.hash==='#newsku')btn.click();
})();
