(()=>{
const $=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),cash=n=>'¥'+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});let latest=null,growthData=null,mode='month';
const style=document.createElement('style');style.textContent=`.savings-visual{border:1px solid #d1e1d2;background:linear-gradient(135deg,#f1f8f1,#fff);padding:20px;border-radius:13px;margin:16px 0}.savings-visual h4{margin:0;font-size:19px}.chart-switch{display:flex;gap:6px;margin:10px 0 16px}.chart-switch button{padding:5px 12px;border:1px solid #d2dacd;border-radius:20px;background:white;cursor:pointer}.chart-switch button.active{background:#2d6942;color:white}.cost-chart-row{display:grid;grid-template-columns:105px 1fr 95px;gap:10px;align-items:center;font-size:12px;margin:13px 0}.cost-chart-track{background:#e7e9e1;height:29px;border-radius:6px;overflow:hidden}.cost-chart-fill{height:100%;background:#b6b0a6;min-width:0;border-radius:6px}.cost-chart-row.fbs .cost-chart-fill{background:#ee4d2d}.chart-highlight{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px}.chart-highlight>div{padding:13px;background:white;border:1px solid #dce7d8;border-radius:10px;font-size:12px}.chart-highlight strong{display:block;font-size:23px;color:#297143}.progress-panel{background:#f7f8f6;border:1px solid #e2e6dc;padding:12px;border-radius:10px;margin:12px 0}.progress-panel h5{margin:0 0 8px;font-size:13px;color:#386b44}.progress-steps{display:flex;flex-wrap:wrap;gap:7px}.progress-step{padding:6px 9px;border-radius:6px;background:#edece8;color:#887f73;font-size:11px}.progress-step.recorded{background:#dfefdf;color:#2e7344}.progress-summary{font-size:12px;margin:8px 0}.progress-panel small{font-size:11px;color:#887f73;display:block}.pickup-qualifications{display:grid;gap:8px;margin:12px 0}.pickup-qualifications p{margin:0;background:#f5f6ee;padding:9px;border-radius:7px}@media(max-width:600px){.chart-highlight{grid-template-columns:1fr}.cost-chart-row{grid-template-columns:70px 1fr 85px;gap:6px}}`;style.textContent+='.ratio-list{display:grid;gap:10px;margin:12px 0;font-size:12px}.ratio-track{height:6px;background:#e2e5dc;border-radius:5px;margin-top:6px}.ratio-track i{display:block;height:6px;background:#498653;border-radius:5px}.incentive-subtitle{padding-top:18px;margin-top:18px;border-top:1px solid #e8e0d7}.sku-placeholder{background:#f8f5ef;border:1px dashed #d9caba;padding:18px;border-radius:12px}.sku-preview-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:12px}.sku-preview-grid>div{font-size:12px;color:#8a8177;background:white;padding:13px;border-radius:8px}@media(max-width:600px){.sku-preview-grid{grid-template-columns:1fr}}';style.textContent+='.pene-how h5{font-size:16px;color:#315d3b;margin:18px 0 8px}.pene-how p{font-size:13px;line-height:1.75}';style.textContent+='.forecast-callout{background:#edf6ec;border:1px solid #cddfca;padding:16px;border-radius:10px;margin-top:12px;color:#32663d}.forecast-callout>b{font-size:18px}.forecast-callout p{font-size:12px;margin-bottom:0}.trial-progress-holder{margin-top:18px}';document.head.append(style);
function chart(){if(!latest?.values)return;const v=latest.values,part=$('#freeTrialPart');if(!part)return;let box=$('#savingsVisual');if(!box){box=document.createElement('div');box.id='savingsVisual';box.className='savings-visual';part.querySelector('.dual-compare')?.before(box)}const qty=mode==='month'?v.u:1,sls=v.sCom+v.sFreight,pf=v.pCom+v.pfFreight+(Number($('#op3pf').value)||0),a=[['FBS',v.total],['3PF',pf],['SLS',sls]],max=Math.max(...a.map(x=>x[1]),1),pct=(x,b)=>b>0?(Math.abs(x)/b*100).toFixed(1)+'%':'—';box.innerHTML='<span class="section-no">FBS SAVINGS AT A GLANCE</span><h4>同样的销量，FBS 能少付多少钱？</h4><div class="chart-switch"><button data-mode="month" class="'+(mode==='month'?'active':'')+'">每月</button><button data-mode="unit" class="'+(mode==='unit'?'active':'')+'">每件</button></div>'+a.map(([name,value])=>'<div class="cost-chart-row '+(name==='FBS'?'fbs':'')+'"><b>'+({FBS:'FBS 官方仓',SLS:'SLS 跨境直邮','3PF':'3PF 三方仓'}[name])+'</b><div class="cost-chart-track"><div class="cost-chart-fill" style="width:'+Math.max(0,value/max*100)+'%"></div></div><b>'+cash(value*qty)+'</b></div>').join('')+'<div class="chart-highlight">'+[['3PF',pf],['SLS',sls]].map(([name,total])=>{const d=total-v.total;return '<div>相较 '+name+' · '+(d>=0?'预计节省':'预计多付')+'<strong style="color:'+(d>=0?'#297143':'#b65536')+'">'+cash(Math.abs(d)*qty)+'</strong>'+(d>=0?'成本降低 ':'成本增加 ')+pct(d,total)+'</div>'}).join('')+'</div><p class="muted">'+(mode==='month'?'按你填写的 '+v.u+' 件 / 月':'每件平均成本')+'；Free Trial 自动预估免费期，仅比较佣金、头程及操作费，不代表已实现收益或完整利润。</p>';box.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;chart()})}
function programKind(card){const t=(card.querySelector('h4')||card.querySelector('summary')||card).textContent;return /New Seller Acquisition|新卖家入仓成长|新卖家成长/.test(t)?'acquisition':/Penetration|占比增长/.test(t)?'pene':/Sea Shipping|头程折扣/.test(t)?'shipping':/Free Pickup|免费揽收|免费搬仓/.test(t)?'pickup':/VIP|重点卖家/.test(t)?'vip':/Free Trial|免费试用/.test(t)?'trial':null}
function statusRows(r,kind){if(['trial','pickup'].includes(kind))return r.progress?.[kind]?[r.progress[kind]]:[];return (r[kind]||[]).map(x=>x.progress).filter(Boolean)}
function relativeBars(p){return p.ratios?.length?'<div class="ratio-list">'+p.ratios.map(x=>'<div><b>'+E(x.label)+' '+Number(x.percent).toFixed(1)+'%</b><div class="ratio-track"><i style="width:'+Math.max(0,Math.min(100,Number(x.percent)))+'%"></i></div></div>').join('')+'</div>':''}
function decorate(root,r){if(!root||!r)return;root.querySelectorAll('.program-cost,.program').forEach(card=>{const kind=programKind(card);if(!kind)return;if(kind==='pickup'){card.querySelector('.progress-panel')?.remove();const benefit=card.querySelector('.program-benefit');if(benefit&&r.pickup)benefit.textContent='首次免费揽收：'+r.pickup.firstStatus+'；多次免费揽收：'+r.pickup.multipleStatus+'。若需免费揽收服务，请找客户经理确认。';return}if(kind==='pene'&&card.querySelector('.pene-how'))return;const rows=statusRows(r,kind);if(!rows.length)return;const sig=JSON.stringify(rows)+JSON.stringify(r.pickup);let panel=card.querySelector('.progress-panel');if(panel?.dataset.signature===sig)return;if(!panel){panel=document.createElement('div');panel.className='progress-panel';card.append(panel)}panel.dataset.signature=sig;const unique=[...new Map(rows.map(x=>[JSON.stringify(x),x])).values()];panel.innerHTML='<h5>卖家目前进展 · 来源表记录</h5>'+unique.map(p=>'<div class="progress-summary"><b>'+E(p.label)+'</b></div><div class="progress-steps">'+p.steps.map(x=>'<span class="progress-step '+E(x.state)+'">'+(x.state==='recorded'?'✓ ':'○ ')+E(x.label)+'</span>').join('')+'</div>'+relativeBars(p)+'<small>'+E(p.note)+'</small>').join('<hr>')+'<small>绿色表示有记录或截至数据日达到参考条件；灰色表示待核验，不等于未完成。仅展示占比或 RR 等相对指标，不展示 ADO、销量、销售额等经营绝对值。</small>';
if(kind==='pickup'&&r.pickup){const p=card.querySelector('.program-benefit');if(p)p.textContent='首次资格（G列）：'+r.pickup.firstStatus+'；多次资格（H列）：'+r.pickup.multipleStatus+'；'+r.pickup.usageStatus;}
})}
function costProgress(){const part=$('#freeTrialPart');part?.querySelector('.trial-progress-holder')?.remove();if(!latest?.data)return;const r=latest.data.sites?.find(x=>x.site===latest.values.s);decorate($('#costPrograms'),r);if(part&&r?.trialDetails?.length){const card=document.createElement('div');card.className='trial-progress-holder';card.innerHTML='<h4>该 GGP 在本站的 Free Trial 店铺（'+r.trialDetails.length+' 家）</h4><div class="shop-list"><table class="table"><thead><tr><th>Shop ID</th><th>Username</th><th>入库日期</th></tr></thead><tbody>'+r.trialDetails.map(x=>'<tr><td>'+E(x.shopId)+'</td><td>'+E(x.username||'—')+'</td><td>'+E(x.firstInboundAfterTrial||'暂未入库')+'</td></tr>').join('')+'</tbody></table></div>';part.append(card)}}
window.addEventListener('cost-preview-update',e=>{latest=e.detail;chart();costProgress()});
const originalFetch=window.fetch;window.fetch=async(...args)=>{const res=await originalFetch(...args);if(String(args[0]).includes('/api/incentives')){res.clone().json().then(x=>{growthData=x;setTimeout(growthProgress,0)}).catch(()=>{})}return res};
function growthProgress(){if(!growthData?.sites)return;const root=$('#programResults');if(!root)return;const groups=root.querySelectorAll('section');groups.forEach(group=>{const title=group.querySelector('h3')?.textContent||'';const r=growthData.sites.find(x=>title.includes(x.site));if(r)decorate(group,r)})}
const root=$('#programResults');if(root)new MutationObserver(growthProgress).observe(root,{childList:true,subtree:true});
// Re-render the populated calculator once after installing visualization listeners.
$('#itemsPerOrder')?.dispatchEvent(new Event('input',{bubbles:true}));
})();
