(()=>{
const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usd=n=>Number.isFinite(n)?'US$ '+n.toLocaleString('en-US',{maximumFractionDigits:2}):'暂无记录';
const pct=n=>Number.isFinite(n)?n.toFixed(0)+'%':'—';
const names={MY:'马来西亚',PH:'菲律宾',SG:'新加坡',TH:'泰国'};
const style=document.createElement('style');style.textContent=`.rvp-year{padding:24px;background:#fff;border:1px solid #eadbd0;border-radius:15px;margin:24px 0}.rvp-year h3{margin:0 0 10px;font-size:25px}.rvp-year h4{font-size:20px;margin:24px 0 12px}.rvp-year>p,.rvp-year .rvp-foot{color:#807264;font-size:13px;line-height:1.7}.rvp-year-scroll{overflow:auto;border:1px solid #e6ddd3;border-radius:10px}.rvp-matrix{border-collapse:separate;border-spacing:0;width:100%;min-width:1040px;font-size:12px}.rvp-matrix th,.rvp-matrix td{padding:12px 7px;text-align:center;border-right:1px solid #eee7df;border-bottom:1px solid #eee7df;min-width:63px}.rvp-matrix thead th{background:#f6f1eb;color:#725c4e}.rvp-matrix .rvp-site{position:sticky;left:0;z-index:2;background:#fff7ef;min-width:100px;color:#ad482e;text-align:left}.rvp-matrix .rvp-site span{display:block;font-size:11px;color:#8d7a68}.rvp-matrix .rvp-target{min-width:86px;background:#faf8f4;font-weight:normal}.rvp-matrix td.met{background:#eaf4e7;color:#367542;font-weight:bold}.rvp-matrix td.partial{background:#fff1df;color:#9e6832}.rvp-matrix td.missing{color:#a2998f;background:#faf9f7}.rvp-matrix .current{box-shadow:inset 2px 0 #ee8064,inset -2px 0 #ee8064}.rvp-matrix thead .current{background:#fff0e6}.rvp-year-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.rvp-year-card{border:1px solid #e9ded4;border-radius:12px;padding:16px;min-width:0}.rvp-year-card h4{margin:0 0 14px;font-size:18px;color:#b5442b}.rvp-year-totals>div{background:#fff3eb;padding:12px;border-radius:8px;font-size:12px;margin:9px 0}.rvp-year-totals>div+div{background:#f3f0f8}.rvp-year-totals strong{display:block;font-size:22px;margin:7px 0;color:#a9412b;overflow-wrap:anywhere}.rvp-year-totals>div+div strong{color:#705687}.rvp-year-totals small{font-size:12px!important}.rvp-mtd-heading{font-size:22px;margin:26px 0 12px;color:#b5442b}@media(max-width:1000px){.rvp-year-grid{grid-template-columns:1fr 1fr}}@media(max-width:550px){.rvp-year{padding:15px}.rvp-year-grid{grid-template-columns:1fr}.rvp-year-totals{display:grid;grid-template-columns:1fr 1fr;gap:8px}.rvp-year-totals strong{font-size:20px}}`;document.head.append(style);
function amountSummary(months,key){const known=months.filter(m=>Number.isFinite(m[key]));return {value:known.length?known.reduce((v,m)=>v+m[key],0):null,}}
function cell(m,key,currentMonth){const future=m.month>currentMonth,values=m.performance.map(p=>p[key]),one=values.length===1?values[0]:null,known=Number.isFinite(one);return `<td class="${known?(one>=100?'met':'partial'):'missing'} ${m.month===currentMonth?'current':''}" title="${E(m.month)} · ${key==='baseline'?'基础':'挑战'}目标达成率">${future?'未开始':known?pct(one):values.length>1?'多条记录':'—'}</td>`}
window.renderRvpYear=(data,sites)=>{
 document.getElementById('rvpYear')?.remove();document.getElementById('rvpMtdHeading')?.remove();const h=data?.rvpHistory;if(!h)return;
 const rows=h.sites.filter(x=>sites.includes(x.site)),s=document.createElement('section');s.id='rvpYear';s.className='rvp-year';
 s.innerHTML=`<p class="kicker">REGIONAL VIP · 年度回顾</p><h3>${E(data.ggpCode)} · ${h.year} 年各站目标达成率</h3><p>横向看每月变化，纵向比较各站。基础与挑战目标分行展示；绿色表示表内达成率 ≥100%，不代表全部奖励条件已满足。读取日期 ${E(h.readAt)}。</p><div class="rvp-year-scroll" role="region" aria-label="站点乘全年月份达成率总表" tabindex="0"><table class="rvp-matrix"><thead><tr><th class="rvp-site" scope="col">站点</th><th scope="col">目标</th>${Array.from({length:12},(_,i)=>{const mo=h.year+'-'+String(i+1).padStart(2,'0');return `<th scope="col" class="${mo===h.currentMonth?'current':''}">${i+1}月${mo===h.currentMonth?'<br>MTD':''}</th>`}).join('')}</tr></thead><tbody>${rows.map(x=>['baseline','stretch'].map((k,i)=>`<tr>${i===0?`<th rowspan="2" scope="rowgroup" class="rvp-site">${E(x.site)}<span>${names[x.site]}</span></th>`:''}<th scope="row" class="rvp-target">${i?'挑战目标':'基础目标'}</th>${x.months.map(m=>cell(m,k,h.currentMonth)).join('')}</tr>`).join('')).join('')}</tbody></table></div><p class="rvp-foot">可左右滑动查看全年。— 表示缺少可用达成率；未开始的月份不计结果。历史按源表 RR 展示，${E(h.currentMonth)} 为 MTD，不能把各月百分比直接相加或当作全年总达成率。</p>${rows.some(x=>x.months.some(m=>m.performance.length>1))?'<p class="rvp-foot">部分月份有多条目标记录，暂不合并达成率，请客户经理核对。</p>':''}<h4>各站累计已返还奖励</h4><p class="rvp-foot">按本年度已有记录累计，单位美元。佣金和广告金分别核算；广告金为推广资源，不与佣金合并为现金收益。</p><div class="rvp-year-grid">${rows.map(x=>{const met=x.months.filter(m=>m.month<h.currentMonth&&m.performance.length===1&&Number.isFinite(m.performance[0].baseline)&&m.performance[0].baseline>=100),months=x.months.filter(m=>m.month<=h.currentMonth),cash=amountSummary(months,'commission'),ads=amountSummary(months,'ads');return `<article class="rvp-year-card"><h4>${E(x.site)} · ${names[x.site]}</h4>${x.site==='TH'?'<p class="rvp-foot">本站 VIP 不设佣金返点</p>':''}<div class="rvp-year-totals">${(x.site==='TH'?[[ads,'广告金']]:[[cash,'佣金'],[ads,'广告金']]).map(([a,label])=>`<div>累计已返还${label}<strong>${usd(a.value)}</strong><small>${a.value===null?'待补充返还记录':'按返还表已有金额累计'}</small></div>`).join('')}</div></article>`}).join('')}</div><p class="rvp-foot">累计奖励按已确认发放的源表金额汇总，空白不补零。</p>`;
 document.getElementById('projectStatus').after(s);
 const heading=document.createElement('h3');heading.id='rvpMtdHeading';heading.className='rvp-mtd-heading';heading.textContent=h.currentMonth+' · MTD 当月进展';s.after(heading);
 const current=document.getElementById('programOverview');if(current)heading.after(current);
};
})();
