(()=>{
const dialog=document.createElement('dialog');dialog.id='projectDetailDialog';dialog.innerHTML='<button class="detail-close" aria-label="关闭项目明细">×</button><div class="detail-content"></div>';document.body.append(dialog);let returnFocus;
dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>returnFocus?.focus());
window.openProjectDetails=el=>{returnFocus=el.querySelector('summary');const content=dialog.querySelector('.detail-content');content.replaceChildren();const title=document.createElement('h3');title.textContent=el.querySelector('h5')?.textContent||'项目明细';content.append(title);const context=document.createElement('p');context.textContent=el.querySelector('.project-context')?.textContent||'';content.append(context);const detail=el.querySelector('.project-expanded').cloneNode(true);detail.querySelectorAll('.project-progress,.milestone-grid').forEach(x=>x.remove());content.append(detail);dialog.showModal();dialog.querySelector('button').focus()};
const journeys=[{name:'完全不了解官方仓',title:'先看懂，再决定是否试仓',desc:'了解一店多运，保留 SLS / 3PF；看入仓步骤，再用商品试算成本。',links:[['guide','了解入仓流程'],['cost','试算一件能省多少'],['appendix','看懂缩写与库存共享']]},{name:'了解官方仓，但还没入仓',title:'从一款商品开始准备',desc:'先试算成本，再查询店铺资格与新卖家激励；有新品名单时，选定备货档位并下载计划。',links:[['cost','计算费用与查询资格'],['growth','核验可参加项目'],['newsku','查看新品与备货计划']]},{name:'已入仓，看激励完成情况',title:'找到当前最值得推进的项目',desc:'输入 GGP Code，查看站点进展；优先看 VIP、新卖家成长，再看 Pene。',links:[['growth','查看我的项目进展'],['newsku','继续提报新品'],['appendix','检查 FBS 标签规则']]}];
const panel=document.createElement('section');panel.className='journey-panel';panel.innerHTML='<div class="journey-heading"><b>您现在处于哪个阶段？</b><span>选一项，快速找到下一步；随时可切换</span></div><div class="journey-choices">'+journeys.map((j,i)=>`<button type="button" data-stage="${i}" aria-pressed="false"><span>0${i+1}</span>${j.name}</button>`).join('')+'</div><div class="journey-next" hidden></div>';document.querySelector('.hero').append(panel);
panel.querySelectorAll('[data-stage]').forEach(btn=>btn.onclick=()=>{const index=Number(btn.dataset.stage),j=journeys[index];panel.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const box=panel.querySelector('.journey-next');box.hidden=false;box.innerHTML=`<div><strong>${j.title}</strong><p>${j.desc}</p></div><div class="journey-links">${j.links.map(([page,label])=>`<button data-destination="${page}">${label} →</button>`).join('')}</div>`;box.querySelectorAll('[data-destination]').forEach(b=>b.onclick=()=>{document.querySelector(`.tabs [data-page="${b.dataset.destination}"]`).click();document.getElementById(b.dataset.destination)?.scrollIntoView({behavior:'smooth',block:'start'})})});
const style=document.createElement('style');style.textContent=`.hero{padding:26px max(22px,calc((100% - 1116px)/2));background:#fff6f0;color:#392c24;border-bottom:1px solid #edd8ca}.hero:after{display:none}.hero h1{font-size:32px;line-height:1.15;letter-spacing:0}.hero h1 br{display:none}.hero h1 em{color:#ee4d2d;margin-left:12px}.hero .eyebrow{color:#c64627}.hero>.pill{display:none}.hero>p{font-size:14px;color:#806b5d}.hero .journey-panel{color:#392c24;margin:18px 0 0;max-width:none}.hero .journey-panel p{font-size:13px;margin:6px 0 12px}.journey-panel{max-width:1116px;margin:22px auto 0;padding:20px;background:#fff;border:1px solid #eadfd5;border-radius:14px}.journey-heading{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px}.journey-heading span{font-size:12px;color:#82756a}.journey-choices{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.journey-choices button{padding:14px 10px;border:1px solid #e4d9ce;background:#faf7f2;border-radius:10px;cursor:pointer;color:#51473f;font-size:14px;text-align:left}.journey-choices button span{color:#ee4d2d;margin-right:9px;font-weight:bold}.journey-choices [aria-pressed=true]{border-color:#ee4d2d;background:#fff0e8;color:#b53e22}.journey-next{padding-top:16px;margin-top:16px;border-top:1px solid #eee0d3}.journey-next p{font-size:13px;color:#786e64;margin:6px 0 12px}.journey-links{display:flex;gap:9px;flex-wrap:wrap}.journey-links button{background:#ee4d2d;color:#fff;border:0;border-radius:7px;padding:9px 13px;cursor:pointer;font-size:13px}#projectDetailDialog{width:min(720px,92vw);max-height:85vh;box-sizing:border-box;overflow:auto;border:1px solid #e0d6cd;border-radius:16px;padding:26px;color:#332b25}#projectDetailDialog::backdrop{background:#22180e70}.detail-close{float:right;position:sticky;top:0;border:0;background:#f4e9df;border-radius:50%;width:34px;height:34px;font-size:23px;cursor:pointer}.detail-content{font-size:14px}.detail-content h3{font-size:22px;margin-top:6px}.detail-content .project-expanded{border:0;margin-top:10px;padding-top:0}.detail-content .project-table-scroll{overflow:auto}.compact-project-grid{align-items:start!important}@media(max-width:780px){.journey-panel{margin:15px 16px 0;padding:15px}.journey-heading{display:block}.journey-heading span{display:block;margin-top:4px}.journey-choices{grid-template-columns:1fr}.journey-choices button{padding:11px}.journey-links{flex-direction:column}#projectDetailDialog{padding:18px}}`;document.head.append(style);
})();

{const s=document.createElement("style");s.textContent="dialog h3{color:#ee4d2d}";document.head.append(s);}
