(()=>{
 const endpoint='https://el-fbs-roster-api.summer-li01.workers.dev/api/events';const random=()=>crypto.randomUUID();let uid;try{uid=localStorage.getItem('fbs.usage.uid');if(!uid){uid=random();localStorage.setItem('fbs.usage.uid',uid)}}catch{uid=random()}
 const sid=random();let module='guide',ggp='',shop='',lastInput=Date.now(),tick=Date.now(),opened=false;
 const context=()=>{try{const x=JSON.parse(localStorage.getItem('fbs.rm.selfdeclared.v1'));if(x&&x.expiresAt>Date.now()&&x.email)return {actor:'rm_self_declared',email:x.email}}catch{}return {actor:'non_rm',email:''}};
 function send(action,seconds=0){const e={id:random(),uid,sid,...context(),ggp,shop,module,action,seconds};fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(e),keepalive:true}).catch(()=>{});}
 function flush(){const now=Date.now(),seconds=Math.min(30,Math.floor((now-tick)/1000));if(opened&&document.visibilityState==='visible'&&now-lastInput<60000&&seconds>0)send('active',seconds);tick=now;}
 window.addEventListener('DOMContentLoaded',()=>{module=document.querySelector('.tabs .on')?.dataset.page||'guide';if(!['guide','cost','growth','newsku','appendix'].includes(module))module='guide';ggp=window.FBSAccess?.isShare?'S'+window.FBSAccess.code:'';opened=true;send('open');if(window.FBSQuery){const original=FBSQuery.request;FBSQuery.request=function(url,body,...rest){flush();if(String(url).includes('free-trial')){module='cost';ggp='';shop=body.shopId||body.username||'';send('query_shop')}else if(/incentives|new-sku/.test(url)){module=String(url).includes('new-sku')?'newsku':'growth';ggp='S'+String(body.ggp||'').replace(/^S/i,'');shop='';send('query_ggp')}return original.call(this,url,body,...rest)}}const footer=document.querySelector('.footer');if(footer){const n=document.createElement('small');n.textContent='本工具记录匿名访客编号、访问板块与有效停留时长，用于改进服务；RM模式按所填邮箱汇总。';footer.append(n)}});
 for(const name of ['pointerdown','keydown','scroll'])window.addEventListener(name,()=>{lastInput=Date.now()},{passive:true});
 setInterval(flush,20000);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){const n=Math.min(30,Math.floor((Date.now()-tick)/1000));if(opened&&Date.now()-lastInput<60000&&n>0)send('active',n)}tick=Date.now()});window.addEventListener('pagehide',()=>{if(document.visibilityState==='visible')flush()});
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.page){flush();module=b.dataset.page;if(['guide','cost','growth','newsku','appendix'].includes(module))send('view');}
 if(b.hasAttribute('data-select'))send(b.getAttribute('aria-pressed')==='true'?'remove_plan':'add_plan');if(b.hasAttribute('data-bulk-tier')||b.id==='skuSelectMinimum')send('select_all');if(b.id==='skuExport'||b.id==='export')send('download');
 },true);
 document.addEventListener('submit',e=>{if(e.target.id==='rmForm'){setTimeout(()=>send('rm_start'),0)}});
})();
